name 'netops-gitlab'
version '0.0.3'
author 'Evgeniy Evtushenko'
license 'UNKNOWN'
summary 'Puppet GitLab module'
description 'This module allows you to manage a GitLab intance with Puppet.'
source 'UNKNOWN'
project_page 'https://crywiki/display/OO/netops-gitlab'
dependency 'puppetlabs-stdlib', '>= 2.3.1'
dependency 'puppetlabs-vcsrepo', '>= 1.1.0'
dependency 'puppetlabs-postgresql', '>= 4.0.0'
dependency 'maestrodev-rvm', '>= 1.6.6'
dependency 'fsalum-redis', '>= 1.0.2'
